- hosts: nodes
  become: yes
  tasks:
  - name: Habilita selinux
    selinux:
     state: enforcing
     policy: targeted
    register: result

  - name: Cria autorelabel
    file: 
     path: /.autorelabel
     state: touch
    when: result.changed == true

  - name: Reboot
    shell: reboot
    when: result.changed == true
