apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0c
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  - ReadWriteMany
  - ReadOnlyMany 
  nfs: 
    path: /exports/pvs/pv0c
    server: ocp-bastion.centrus.org.br
  persistentVolumeReclaimPolicy: Retain
