apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1c
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  - ReadWriteMany
  - ReadOnlyMany 
  nfs: 
    path: /exports/pvs/pv1c
    server: ocp-bastion.centrus.org.br
  persistentVolumeReclaimPolicy: Retain
